### ISSUE TITLE
samba username & password

### ISSUE THREAD

**Issue by drrak** [bite-your-idols/Gamestarter-Pi#10]
Google translator:
After using the emulator and return to Kodi, I noticed that the samba password and the username is changed to default.

**Comment by bite-your-idols** [comment]
how did you changed them in first place? using retroarch or using kodi? what distro are you using, libreelec or oepnelec? and what version?

**Comment by drrak** [comment]
Kodi, more precisely:
OpenELEC Settings > Services > Use Samba Password...

OpenELEC 6.0.3, RPi2

**Comment by bite-your-idols** [comment]
ok, you're right. I have test it in my installation (OE 6.0.3 also) and it happened to me. I'll try to detect where the problem is.

**Comment by bite-your-idols** [comment]
If I use the default retroarch version 1.3.2 I can change samba username and pass and then enter retroarch, play a game, exit retroarch and it stills have custom data. The issue only happens when using latest retroarch version extracted from lakka, v1.3.4.
Please check which version are you using.
In LibreELEC 8/kodi 17 alphas it works ok also.

**Comment by drrak** [comment]
That's right, my version is 1.3.4. I'd rather stick with OE 6.0.3.

**Comment by bite-your-idols** [comment]
In /storage/.kodi/addons/script.gamestarter/resources/bin/ folder you will find retroarch 1.3.2 binary, you can rename it to retroarch and give it permissions, then you can use that version and change your smb user/pass, this change will persist.

**Comment by bite-your-idols** [comment]
In latest release I included new retroarch 1.3.4 binary compiled without lakka stuff, so this issue not happens anymore.
