### ISSUE TITLE
HDMI-CEC

### ISSUE THREAD

**Issue by kathiedart** [bite-your-idols/Gamestarter-Pi#20]
Hi,

I use HDMI-CEC for Kodi and love being able to use my TV remote.

Is there any chance of being able to use it for GSP?

**Comment by bite-your-idols** [comment]
Since HDMI-CEC is a kodi feature it does not work once you exit kodi and start retroarch or emulationstation... There was a user that implemented some custom libcec library and it worked even you exit kodi, you can take a look here:
https://www.youtube.com/watch?v=9SR2DvcZF3I&list=FLiXMfGdMmWtGcrzXbseefNQ&index=5
