### ISSUE TITLE
(v2.5) Updating Breaks Things!

### ISSUE THREAD

**Issue by chewvodka** [bite-your-idols/Gamestarter-Pi#22]
Just got the email that v2.5 is available.  Downloaded the standard OpenELEC release, and manually updated in Kodi via "Install from Zip.  All of the customizations I made to the previous installation are now gone.  I suspect this is because you mention in the release notes that the config files are now being moved to /userdata instead of /config.  Did the upgrade completely erase the previous config file, and if not, can I just move it to the new path or will that not work?  Also, I'm trying to use the new install of RetroArch (still the same version of 1.3.6) to Re-Add my scanned paths for each console, but after completing a scan nothing appears.  I thought I remembered a discussion of this happening before and the solution was to re-download the databases.  I did that, but nothing works.  I also now have listings in my /storage/emulators path for other systems I never installed (like Amiga, Atari, MSX, etc).  Did the new installation create these new paths, and are they safe to erase?

I always like new updates because it brings in new stuff, but it looks like this update might be having a hiccup.  I can see the benefits of the direction it's going, but if I can't add my content to RetroArch, I'm stuck!

Chewvodka aka Hansolo77

**Comment by chewvodka** [comment]
Not sure why the playlists aren't scanning, but I was able to restore my existing playlists by copying from the .config/retroarch/playlists to the new path of .kodi/userdata/addons/script.gamestarter/retroarch/playlists. Perhaps the databases are getting corrupted during the download/extract.  All I know is, the 30 or so games I have on my SD card are now showing up.

I'm in the process now of copying over my .config/retroarch/thumbnails path to the new location.  It looks to me like this could have been avoided by adding lines to the install/update script to MOVE these files out of the old locations and into the new ones rather than needing to recreate them.  Just a heads up.  Hope to see more updates.  I'll report back if I find any other issues.  In fact, I'm going to bed now so I'll see if anything new is updated here tomorrow around 5pm EST.

**Comment by bite-your-idols** [comment]
hi hansolo!
Thanks fot this quick test & feedback :)
This new release has a lot of path chages and can be a little complicated.  
The best way to update is using addon setings update feature but before you must need to backup your config files. This is why I included a new backup/restore feature.

About your issues, lets see them one by one:

- Your files are not erased, if you updated via zip,they are in /.config folder, you can copy/paste them into userdata folder, but you will need to change some lines in retroarch.cfg

-Playslists past issue was related with wrong paths in retroarch.cfg file, it is not your problem now. I think your problem is that you need to download databases from retroarch menu (doanload content/update databases/) to allow retroarch fetch your roms with. If you manually move your /.config/retroach folders to new location, they will show up also. It this does not work, please activate retroarch debuggin and see what is inside gamestarter.log (now moved to userdata).

- You can delete paths you are not going to use from emulators/roms, thay are always created by default to let know users how to name folders in case of using emulationstation or/and AdvancedLauncher.

- All your old config files are moved to new location before new installation if you use the addon settings update feature, I put tose lines there instead in installation script because are related with updateing users not with new installations... But yes, I agree, this new version needs some kind of update explanation.

Yhank you very much for your feedback!!

**Comment by chewvodka** [comment]
Not a problem.  Moving the playlists folder and the thumbnails folder into the new path fixed it.  I'm thinking I might start from scratch again though, and completely wipe all instances of Gamestarter and RetroArch to be safe.  Is everything inside /.config now safe to erase, or is there still a reason to keep files in there (obviously I want to keep everything not related to this)?  It looks like everything (as in RetroArch) is now installed inside the script.gamestarter paths.  Is this correct?

**Comment by bite-your-idols** [comment]
Yes, everything is now installed in userdata folder, also log file. You can remove retroarch and emulationstation folders, and the symlink of advancedlauncher.

After 2.5 installation some symlinks are created:
- one for retroarch default system folder in .config
- one for emulationstation in same .config folder
- another for emulationstation in storage folder for the scraper.

Note that both emulationstation symlinks are created during its own installation from addon settings and this is why a fresh emulationstation re-installation is recommended after 2.5 updating and installation.

Remember that once you have all folder inside userdata (after updating or manually moving) you can backup all your data from addon settings, and later restore them.

**Comment by chewvodka** [comment]
Cool.  I don't use emustation or advanced launcher, so I'll just remove those.  Thanks for the heads up!
