### ISSUE TITLE
hotkeys - mapping to joypad

### ISSUE THREAD

**Issue by drrak** [bite-your-idols/Gamestarter-Pi#27]
_Google translator:_
Is there a quick and simple way to set these hotkeys? Earlier I edited the file retroarch.cfg, but now I have blocked access to this file.

Gamestarter v2.5
LibreELEC 7.0.2, RPi2

**Comment by bite-your-idols** [comment]
you can assign hotkeys for global retroarch config (retroarch.cfg) or for just your gamepad config file (autoconfig/your_gamepad_name.cfg). Also you can edit this values in retroarch menu. 
Please read some info/help about RetroArch configurations and settings because this is not related directly with script addon.
