### ISSUE TITLE
Playlist - cannot Scan Directory or Add Content

### ISSUE THREAD

**Issue by Stavr0** [bite-your-idols/Gamestarter-Pi#43]
_Steps:_
Choose **Add Directory**
Navigate to **NES/** folder
Choose **Scan Directory**

_Expected:_
**NES/** folder should show items
**Scan Directory** should create Playlist items

_Actual:_
No items in **NES/** folder
No Playlist items added

_Notes:_
RPi 3B running OpenELEC 7
GameStarter 2.6 OLE
Patched for Issue #41  retroarch 1.3.6_LE7
**Load Core** / **Load Contents** works normally
History items are populated and work normally

**Comment by bite-your-idols** [comment]
before add directory you need to go to retroarch online updater and download databases for systems you want to create playlist. After that, you can scan your folders. 

Take note an issue can happen: if scanning freezes your pi, please reboot and create manually this folder:
/storage/.kodi/userdata/addon_data/script.gamestarter/retroarch/playlists

Some user reported me this issue and it will be fixed in next update.

**Comment by Stavr0** [comment]
One hurdle down.
The playlist item now load up but there is no counter to show progress or it's hidden. (Can't seem to get rid of overscan)

__New problem:__
The playlist items crash out of Retroarch back into Kodi
Load Content/Core still OK

**Comment by bite-your-idols** [comment]
please reboot and create manually this folder:
/storage/.kodi/userdata/addon_data/script.gamestarter/retroarch/playlists

About progress, it displays in yellow in the left bottom corner, as jopad info, remappings...

**Comment by Stavr0** [comment]
The folder **playlists** exists,

[Uploading gamestarter.zip…]()
