### ISSUE TITLE
Playlist - Crash on Run Item

### ISSUE THREAD

**Issue by Stavr0** [bite-your-idols/Gamestarter-Pi#44]
**Steps:**
Navigate to __Playlists__
Select Item (NES - Super Mario 3)

**Expect:**
Game Starts

**Actual:**
Retroarch crashes and returns to Kodi

**Notes:**
RPi 3B running OpenELEC 7
GameStarter 2.6 OLE
Patched for Issue #41 retroarch 1.3.6_LE7
Load Core / Load Contents works normally
History items are populated and work normally
Playlist folder exists and is populated with items

**gamestarter.log**

> RetroArch [INFO] :: Found joypad driver: "udev".
> RetroArch [INFO] :: ALSA: Using signed 16-bit format.
> RetroArch [INFO] :: ALSA: Period size: 768 frames
> RetroArch [INFO] :: ALSA: Buffer size: 3072 frames
> RetroArch [INFO] :: ALSA: Can pause: no.
> RetroArch [INFO] :: Found menu display driver: "menu_display_gl".
> RetroArch [INFO] :: Querying GL extension: ARB_framebuffer_object => doesn't exist
> RetroArch [INFO] :: Using font rendering backend: freetype.
> RetroArch [INFO] :: Using font rendering backend: freetype.
> RetroArch [INFO] :: SRAM will not be saved.
> RetroArch [INFO] :: null: [/storage/.kodi/userdata/addon_data/script.gamestarter/retroarch/content_history.lpl].
> RetroArch [INFO] :: [GL]: VSync => on
> RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
> RetroArch [INFO] :: [GL]: VSync => on
> RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
> Segmentation fault (core dumped)
> ::Gamestarter:: -> disable alsa...
> ::Gamestarter:: -> restart kodi...

**Comment by Stavr0** [comment]
**content_history.lpl**

> /storage/emulators/roms/gb/pokemon_-_silver_version.zip
> 
> /storage/.kodi/addons/script.gamestarter/resources/bin/libretro-cores/gambatte_libretro.so
> Gambatte
> 
> 
> /storage/emulators/roms/nes/Super_mario_brothers3.nes
> 
> /storage/.kodi/addons/script.gamestarter/resources/bin/libretro-cores/fceumm_libretro.so
> FCEUmm
>

**Comment by bite-your-idols** [comment]
wow, very well documented issue. Thanks.
one previous question: did you update manually cores using retroarch online updater? this can produce seg fault for cores since they are not optimized for RPi.

If not, you can try to go to retroarch settings>plyalists and check if your playslists are assigned to proper cores, or try with another cores for those systems.

Another hardcore option is to remove retroarch config file (rename it) and launch retroarch, it will create a new config file, maybe there are some corrupted lines in actual config file or any mistaken data in playslist lines in the file.



Finally, there is no need to do this in LibreELEC, it is just for OpenELEC:
-Patched for Issue #41 retroarch 1.3.6_LE7

**Comment by Stavr0** [comment]
Had to patch for #41 otherwise it wouldn't load at all.

Here's the entry for SMB3 
```
/storage/emulators/roms/nes/Super_mario_brothers3.nes
Super Mario Bros. 3 (USA) (Rev A)
DETECT
DETECT
0B742B33|crc
Nintendo - Nintendo Entertainment System.lpl
```

**Comment by bite-your-idols** [comment]
> Had to patch for #41 otherwise it wouldn't load at all.
yes, you are right, my mistake, you said you use OpenELEC.

go to retroarch>settings>playlists and assign "FCEumm" core  to "Nintendo - Nintendo Entertainment System" playlist

**Comment by Stavr0** [comment]
Did that and the Playlist items are now working. Thanks!

I think the initial install of Retroarch needs to have a few more defaults setup to avoid unnecessary debugging,
