### ISSUE TITLE
Documentation for building?

### ISSUE THREAD

**Issue by mx** [bite-your-idols/Gamestarter-Pi#51]
Hey there,

This project looks great! Sadly I'm in possession of an Odroid C2, rather than a Raspberry Pi. I was wondering if you could document the steps you took to build the component pieces (just a list of projects to download and compile into the shared objects would be sufficient), so I could compile them using my own cross-compiler to hopefully get it to work for the C2. The way you packaged it together is fabulous, and I would love to reuse that!

**Comment by bite-your-idols** [comment]
Hi! Firstly, thank you for your interest.
These are the "components" this project includes:
- RetroArch -> compiled by myself using both LibreELEC and OpenELEC toolchain.
- RetroArch cores -> some of them compiled by my but most of them grabbed from Lakka, RetroPie and [Escalade's Build](https://forum.libreelec.tv/thread-302.html)
- Emulationstation -> grabbed from [Escalade's Build](https://forum.libreelec.tv/thread-302.html)
- Some distributable BIOS garbbed from RetroPie
- UAE4ARM amiga emulator binary from [Escalade's Build](https://forum.libreelec.tv/thread-302.html)
- DraStic emulator grabbed from RetroPie
- Advanced Emulator Launcher and Advanced Launcher addons for kodi

And to make all of this work you will ned to take a look to the following scripts:
- gamestarter.sh and gamestarter.start -> these are the bash scripts that launch emulators.
- install.sh -> first-time setup script in order to unzip all components, create folders, permissions...
- install_extras.sh -> online hosted file, called from addon to make optional installations.
- compile.sh ->this is a bash script I made to help me to create all zips and structure for final addon release package
- other bash scripts and python scripts to update, restore...

I think thats all! If you need more info, please let me know.
