### ISSUE TITLE
make GamestarterPi platform independent | merging with other project(s)

### ISSUE THREAD

**Issue by DJCrashdummy** [bite-your-idols/Gamestarter-Pi#63]
_just my 2 cents!_

i accidentally came across your nice project as i did some research about Kodi in conjunction with retrogaming...
as i also saw in this projects issues there is a demand for retrogaming beside a JeOS (#2 and #30) and beside on the raspberrys (#23 and #19); and there are some projects which try to accomplish this: https://www.libretro.com/index.php/powered-by-libretro/
for me it seems [RetroPlayer](http://forum.kodi.tv/forumdisplay.php?fid=194) is a platform independent equivalent of GamestarterPi, so why not join forces, make RetroPlayer ready for prime time and retrogaming easily available for every Kodi-user?

_btw: just to make some things clear... i'm sadly not a developer, i only used RetroPie until now and additionally just know Recalbox and obviously libretro/RetroArch/Lakka. and i also have hardly an idea which project uses which backends and in which way._

**Comment by bite-your-idols** [comment]
I just own my tiny Pi 2 so i can not test/develop for any other platform, also I not a linux developer, just a guy using PI+Kodi who wanted to play retro games without changing OS or SD, so I achieve it learning how to make  retroarch and emulationstation work in LibreELEC/OpenELEC.
About another OS, I don't use them and I don't know how to write code for them, again, I am not a linux developer just a web "designloper".

About retroplayer, I tested it and I am thinking about how to integer both systems but for the moment I see retroplayer is missing a lot of features retroarch has.

One more time, if anyone knows how to port my script (and wants to do it) I am open to receive Pull Request in order to make the addon available for more devices/OS...

**Comment by DJCrashdummy** [comment]
> I not a linux developer, ... , so I achieve it learning how to make retroarch and emulationstation work in LibreELEC/OpenELEC.

kudos! this makes GamestarterPi even more impressive.

>  About another OS, I don't use them and I don't know how to write code for them, ...

well, since RetroPlayer is platform independent i hope this is not that important; i know Kodi is using python (for addons), so python is for sure necessary.

> About retroplayer, I tested it and I am thinking about how to integer both systems but for the moment I see retroplayer is missing a lot of features retroarch has.

unfortunately i haven't found anything about the differences between GamestarterPi and RetroPlayer...

**Comment by bite-your-idols** [comment]
Retroplayer is an integration of libretro cores into kodi as a game player.
Gamestarter installs retroarch and libretro cores in your pi, also emulationstation.

They both achieve the same, so I don't get the point in trying to integer both. In gamestarter you have all workingcores from lakka (Official retroarch distro) and you can configure all settings from retroarch, the frontend. A lot of these settings, by the moment, are not configurables in retroplayer.

The point of Retroplayer is to play games within kodi and you can launch them also using Advanced emulator launcher addon o even IARL addon. I think using emulationstation or retroplayer (what means exiting kodi) is not fitting with retroplayer philosophy.

**Comment by DJCrashdummy** [comment]
thanks for the little explanation of the projects.

**Comment by bite-your-idols** [comment]
RetroArch addon for RetroPlayer: https://github.com/bite-your-idols/game.retroarch
EmulationStation addon for RetroPlayer: https://github.com/bite-your-idols/game.emulationstation
